language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # pipenv seems to have issues on pypy2
  # - "pypy"
  - "pypy3"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install --upgrade pip pipenv
  - pip freeze
  - make setup
  - pipenv run pip freeze

script:
  - make ci

