language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyYAML doesn't install on 3.7
  # - "3.7-dev"
  # pipenv seems to have issues on pypy2
  # - "pypy"
  - "pypy3"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv --version
  - make setup

script:
  - make ci

